---
title: 'Estimating excess bereavement due to Covid-19'
subtitle: 'Grant proposal draft'
author: "Diego Alburez-Gutierrez and Ivan Williams"
date: "15 May 2019"
output:
  pdf_document:
    fig_caption: yes
header-includes: \usepackage{todonotes}
bibliography: bib.bibtex
urlcolor: blue
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE,
                      message=F, warning=F, echo = F)
```

**Outline of grant proposal for Volkswagen's "Corona Crisis and Beyond – Perspectives for Science, Scholarship and Society" grants**

- [Website](https://www.volkswagenstiftung.de/en/funding/our-funding-portfolio-at-a-glance/corona-crisis-and-beyond-perspectives-for-science-scholarship-and-society)
- Amount: up to 120,000 Euro (flexible use)
- Deadline: June 4 2020
- Proposal: 4-page project description
- Team (up to three members): Diego Alburez, Ivan Williams, Emilio Zagheni (?)

## Introduction

Death and bereavement have come to the forefront of public debate as the world grapples with the global pandemic of the Covid-19 disease, which has already brought about the death of thousands of mainly elderly people. 
Each death is meaningful in itself, but it also represents the loss of somebody's parent, grandparent, great-grandparent, aunt, uncle, cousin, or child.
Studies in sociology and public health have consistently shown the negative and long-term consequences of bereavement on mental, physical, and emotional health, especially for women [@umberson_death_2017].
Bereavement also matters because relatives are crucial providers of social and financial support, the loss of which affects the individuals left behind [@Hendrickson2009].




Much attention has been given to Covid-19 excess mortality rates, but little is known about how the pandemic will increase the exposure to death for people around the world.
For many people living in the Global North this will be their first close encounter with death, as historically low mortality rates have implied a reduction in the exposure to mortality at all ages in high-income countries [@murphy_long-term_2011; @alburez_gutierrez_womens_2019].
For people in the Global South, it will add to an already high burden of bereavement [@smith-greenaway_maternal_2020; @roberton_early_2020].



This project will combine existing and future data on Covid-19 excess mortality with powerful methods from formal demography [@goodman1974] to estimate the burden of Covid-19 bereavement.
The project is not interested in the total number of people who will die with Covid-19, but in the number of people who will be affected by the death of a relative because of the disease.
We call this phenomenon `excess bereavement'.
We ask: 

   1. How many people will lose a relative to Covid-19, either in the nuclear or in the extended family? 
   1. Which demographic groups will be at a higher risk of losing a relative to Covid-19 and how will this vary by type of relative lost?
   1. How will excess bereavement affect the availability of family resources for those that survive the disease?

<!-- 2. What is the expected age distribution of the bereaved population? -->

## Project description

### Methodological component

We seek to generalize the Kin-Cohort Method [@alburez_gutierrez_womens_2019], itself an extension of the Goodman, Keyfitz Pullum kinship equations [@goodman1974], to estimate the potential increase in the exposure to the death of relatives given a set of age-specific Covid-19 mortality rates. 
A first step will focus on deriving mathematical expressions to model the effect of changes in mortality on the population-level prevalence of excess bereavement.

\todo[inline]{This comes from our working paper with Ivan}
We exemplify this for the case of parental bereavement - the loss of a child from the perspective of a parent. 
Let $CS_a$ be the expected number of surviving children to a mother alive at age $a$ in a female stable population with fertility rates $m_{x}$, mortality hazard $\mu_{x}$ and survival function $l_x=e^{-\int_{0}^{x}{\mu_t}\,dt}$ (with unit radix $l_0=1$), as proposed by @goodman1974:

$$CS_a = \int_{0}^a{m_{x}l_{a-x}dx}.$$

Now consider an absolute increase in mortality $\delta$ in mortality in the range $[0,a-\alpha]$, where $\alpha$ is the start age of fertility risk.
We can think of this hypothetical increase in mortality as the all-age excess mortality derived from the Covid-19 disease so that $m_{x,\delta}=m_{x}+\delta$ (@wrycza2012) and $l_{a-x}^\delta = e^{-\int_{0}^{a-x}{(\mu_t+\delta})dt}$:

$$CS_{a}^\delta = \int_{\alpha}^{a}m_{x} l_{a-x} e^{-\delta (a-x)} dx.$$

As we have shown elsewhere [ref to our working paper], we can conceptualize the effects of this absolute change $\delta$ in mortality as the difference between maternal age $a$ and the mean age of the mother at the birth of her surviving daughters $k_a$:

<!-- Si sacamos nuestro paper como pre-print, lo podemos citar aqui!! -->

$$\frac{\Delta CS_{a}}{CS_{a}} \approx -(a - k_a) \Delta\delta.$$


We seek to derive these formal relationships for other types of relative (mothers, grandmothers, siblings, cousins, and aunts) to enable the empirical analysis of Covid-19 excess bereavement. 
Further development is needed to consider age-specific changes in mortality, as the Covid-19 disease affects mainly people in older ages and the model presented above assumes a uniform mortality change at all ages.
Finally, the existing models ignore heterogeneity in the experience of kin death and within-group correlations.
This is a limitation considering that deaths from infectious disease are likely to be clustered in the population.
The final strand of the methodological component of the project will dress these issues.

### Empirical component

We will estimate the excess burden of kin death from the Covid-19 disease using our novel mathematical models with mortality and fertility rates as inputs.
Combining this with data on the age and sex structure of the population will allow us to estimate the magnitude of the excess bereavement and the age distribution of the bereaved population\footnote{`Excess' bereavement can be compared to a baseline counter-factual scenario using rates that exclude the excess mortality from Covid-19.}.



As an initial step, the analysis will focus on Germany and Italy, for which quality data on Covid-19 death rates is already available.
Further development will extend our innovative methodology to other setting once reliable data on Covid-19 excess mortality becomes available. 
The project will produce a range of estimates to reflect the uncertainty inherent to the Covid-19 mortality statistics that are required as input. 
However, we expect the accuracy of our models to improve as more data quality becomes available.



## Expected main results

- A flexible and scalable methodology for estimating the excess burden of Covid-19 bereavement. The open-source code to produce the estimates will be freely available on the code-sharing platform [Github](www.github.com).
- The first set of estimates of how the Covid-19 disease will affect the exposure to mortality at a population-level
- A set of academic publications describing the methodology and the main results of the project
- A online platform for scientists and policy makers to access and download the data easily (see [this interactive app](https://research-app.shinyapps.io/child_death_paa/) from one of the authors)

<!-- DIAGRAMA DE PARENTEZCO, DONDE EL EFECTO DE MORTALITYDAD ES LA FLECHA Y EL NODO EL NUMERO ESPERADO DE FAMILIARES -->


## References

